" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vimrc/my_configs.vim

if !has('nvim')
    set runtimepath+=~/vimrc

    "source ~/vimrc/vimrcs/basic.vim
    "source ~/vimrc/vimrcs/filetypes.vim
    "source ~/vimrc/vimrcs/plugins_config.vim
    "source ~/vimrc/vimrcs/extended.vim

    if !has('ide')
        " Minimalist-TabComplete-Plugin
        inoremap <expr> <Tab> TabComplete()
        fun! TabComplete()
            if getline('.')[col('.') - 2] =~ '\K' || pumvisible()
                return "\<C-y>"
            else
                return "\<Tab>"
            endif
        endfun

        " Minimalist-AutoCompletePop-Plugin
        set completeopt=menu,menuone,noinsert
        inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"
        autocmd InsertCharPre * call AutoComplete()
        fun! AutoComplete()
            if v:char =~ '\K'
                \ && getline('.')[col('.') - 4] !~ '\K'
                \ && getline('.')[col('.') - 3] =~ '\K'
                \ && getline('.')[col('.') - 2] =~ '\K' " last char
                \ && getline('.')[col('.') - 1] !~ '\K'

                call feedkeys("\<C-P>", 'n')
            end
        endfun
    endif
endif


" nmap oo m`o<Esc>``
" nmap <S-CR> m`o<Esc>``

" press hh to return to normal mode when in insert mode
inoremap hh <esc>

" press hh to return to normal mode when in visual mode
vnoremap hh <esc>

" press hh when in command mode, to go back to normal mode
cnoremap hh <esc>

vnoremap <leader>(( <esc>`>a)<esc>`<i(<esc>
vnoremap <leader>[[ <esc>`>a]<esc>`<i[<esc>
vnoremap <leader>{{ <esc>`>a}<esc>`<i{<esc>
vnoremap <leader>"" <esc>`>a"<esc>`<i"<esc>
vnoremap <leader>'' <esc>`>a'<esc>`<i'<esc>
vnoremap <leader>`` <esc>`>a`<esc>`<i`<esc>

noremap <leader>y "*y
noremap <leader>p "*p
noremap <leader>y "+y
noremap <leader>p "+p
noremap QQ :q!<cr>
noremap WQ :wq<cr>

nnoremap <Leader>o o<Esc>0"_D
nnoremap <Leader>O O<Esc>0"_D

vnoremap <silent> <leader>r :call VisualSelection('replace', '')<CR>
