-- Load immediately after startup
require("configs.theme")

-- Defer loading until after vim has started
vim.defer_fn(function()
  require('configs.common')
  require('configs.snippets')
  require("configs.cmp")
  require("configs.json")
  require("configs.search_fold")
  require("configs.filter")
  require('configs.completeCurrentLine')
  require("configs.gitsigns")
  require("configs.lsp")
  require("configs.null-ls")
  require("configs.treesitter")
  require("configs.telescope")
  require("configs.peek")
  require('configs.test')
  require('configs.file')
  require('configs.refactor')
  require('configs.dressing')
  require('configs.terminal')
  --require('configs.copilot')
  require('configs.textobjects')
  require('configs.floaterm')
end, 0)
